name: Deploy Storybook and Playwright Reports

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://pnpm.io/continuous-integration#github-actions
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright deps
        run: pnpm playwright install --with-deps chromium

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Start Storybook
        run: |
          pnpm storybook &
          STORYBOOK_PID=$!
          echo $STORYBOOK_PID > storybook.pid

      - name: Wait for Storybook to be ready
        run: pnpx wait-on http://localhost:6006

      - name: Run Playwright tests
        run: pnpm playwright test

      - name: Stop Storybook
        run: |
          kill $(cat storybook.pid)

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-$VERSION
          path: ./storybook-static

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Storybook and Playwright report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-$VERSION
